finos/messageml-utils

src/main/java/org/symphonyoss/symphony/messageml/markdown/MarkdownParser.java
src/test/java/org/symphonyoss/symphony/messageml/MessageMLContextTest.java

MML-34  Overzealous stripping of MD newlines

---

src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
src/test/java/org/symphonyoss/symphony/messageml/MessageMLContextTest.java

Forbidding the usage of class resolution to prevent exploits from malicious templates.

PLAT-4320 Fix Freemarker Vulnerabilities

---

src/main/java/org/symphonyoss/symphony/messageml/elements/Element.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Styles.java
src/test/java/org/symphonyoss/symphony/messageml/elements/ElementTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/StylesTest.java

PLAT-4716 Added the style global attribute

---

src/main/java/org/symphonyoss/symphony/messageml/elements/TextNode.java
src/test/java/org/symphonyoss/symphony/messageml/elements/CodeTest.java

PLAT-4532 Added a check to keep newlines if the text has code as parent

---

src/main/java/org/symphonyoss/symphony/messageml/elements/CashTag.java
src/main/java/org/symphonyoss/symphony/messageml/elements/HashTag.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Keyword.java
src/test/java/org/symphonyoss/symphony/messageml/elements/CashtagTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/HashtagTest.java

MML-76 Relax keywords verification rules

---

src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Button.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Form.java
src/main/java/org/symphonyoss/symphony/messageml/markdown/MarkdownRenderer.java
src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/ButtonNode.java
src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/FormNode.java
src/test/java/org/symphonyoss/symphony/messageml/elements/ButtonTest.java

This PR adds the first of a series of new tags "Symphony Elements". Notice that it is not completely functional by itself, since it requires the "form" tag, that will be included by task APP-2055. This contains, however, complete parsing validation for the "button" tag, and is ready to receive the new Form tag's code.

MML-81 Add the Symphony Elements "button" tag

---

src/main/java/org/symphonyoss/symphony/messageml/elements/Button.java
src/test/java/org/symphonyoss/symphony/messageml/elements/ButtonTest.java

Replaced all "id" attributes in <button> tags for "name" as the new spec defines.

MML-81 Replace the "id" attribute of the "button" tag with "name"

---

src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Button.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Form.java
src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/FormNode.java
src/main/java/org/symphonyoss/symphony/messageml/util/IDataProvider.java
src/main/java/org/symphonyoss/symphony/messageml/util/IUserPresentation.java
src/test/java/org/symphonyoss/symphony/messageml/elements/ButtonTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/FormTest.java
src/test/java/org/symphonyoss/symphony/messageml/util/TestDataProvider.java
src/test/java/org/symphonyoss/symphony/messageml/util/UserPresentation.java

Adding the form tag of Symphony Elements. The interactionUrl field must be provided by a DataProvider.

MML-89 Add the Symphony Elements "form" tag

---

.travis.yml
src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Button.java
src/main/java/org/symphonyoss/symphony/messageml/markdown/MarkdownRenderer.java
src/test/java/org/symphonyoss/symphony/messageml/MessageMLContextTest.java
src/test/resources/payloads/expanded_single_jira_ticket.entities
src/test/resources/payloads/expanded_single_jira_ticket.entityjson
src/test/resources/payloads/expanded_single_jira_ticket.markdown
src/test/resources/payloads/expanded_single_jira_ticket.messageml
src/test/resources/payloads/expanded_single_jira_ticket.presentationml

Fixes https://github.com/symphonyoss/messageml-utils/issues/92

MML-92 Parsing complex PresentatioML fails

---

.github/CONTRIBUTING.md
LICENSE
NOTICE
README.md

aligning README.md and CONTRIBUTING.md to FINOS project blueprint language

MML-103 Align README.md and CONTRIBUTING.md with FINOS project blueprint language

---

pom.xml
src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
src/main/java/org/symphonyoss/symphony/messageml/elements/TextArea.java
src/test/java/org/symphonyoss/symphony/messageml/elements/TextAreaTest.java

Addresses https://github.com/symphonyoss/messageml-utils/issues/112.

MML-112 - Add the Symphony Element 'textarea' tag

---

src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Password.java
src/test/java/org/symphonyoss/symphony/messageml/elements/PasswordTest.java

Addresses https://github.com/symphonyoss/messageml-utils/issues/116.

MML-116 - Add the Symphony Element "password" tag

---

pom.xml
src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Password.java
src/main/java/org/symphonyoss/symphony/messageml/elements/TextField.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/PasswordTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/TextFieldTest.java

* Adding support to pass a default value on input text as an attribute: "value"
* Adding support to pass a default value on text-field as the tag content

PLAT-7964 Initial value of element as content of text-field and password tags

---

src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Element.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Form.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/ButtonTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/FormTest.java

Fixes https://github.com/symphonyoss/messageml-utils/pull/141.

MML-133 - Elements must have unique ids

---

pom.xml

Fixes https://github.com/symphonyoss/messageml-utils/issues/138.

MML-138 - update jackson-databind dependency to 2.9.9.1

---

pom.xml

Addresses issue https://github.com/symphonyoss/messageml-utils/issues/149.

MML-149 - bump jackson-databind to 2.9.9.2

---

src/main/java/org/symphonyoss/symphony/messageml/elements/Button.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/ButtonTest.java

MML-152 - Stop lowercasing button attributes

---

src/main/java/org/symphonyoss/symphony/messageml/elements/Button.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Form.java
src/test/java/org/symphonyoss/symphony/messageml/elements/ElementTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/ButtonTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/CheckboxTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/DateSelectorTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/FormTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/PersonSelectorTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/RadioTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/SelectOptionTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/TextAreaTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/TextFieldTest.java

MML-154 Reject any form without an Action button

---

src/main/java/org/symphonyoss/symphony/messageml/elements/Styles.java
src/test/java/org/symphonyoss/symphony/messageml/elements/StylesTest.java

Fix for https://github.com/symphonyoss/messageml-utils/issues/174

MML-174 Allow url in style property values

---

src/main/java/org/symphonyoss/symphony/messageml/elements/Button.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/ButtonTest.java

See https://github.com/symphonyoss/messageml-utils/issues/175

MML-175 Element Button - Allow more class into the messageml-utils

---

src/main/java/org/symphonyoss/symphony/messageml/elements/Card.java
src/main/java/org/symphonyoss/symphony/messageml/elements/CardBody.java
src/main/java/org/symphonyoss/symphony/messageml/elements/CardHeader.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Chime.java
src/main/java/org/symphonyoss/symphony/messageml/elements/DateSelector.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Element.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Entity.java
src/main/java/org/symphonyoss/symphony/messageml/elements/FormElement.java
src/main/java/org/symphonyoss/symphony/messageml/elements/HorizontalRule.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Image.java
src/main/java/org/symphonyoss/symphony/messageml/elements/LineBreak.java
src/main/java/org/symphonyoss/symphony/messageml/elements/MessageML.java
src/main/java/org/symphonyoss/symphony/messageml/elements/PersonSelector.java
src/main/java/org/symphonyoss/symphony/messageml/elements/RegexElement.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Select.java
src/main/java/org/symphonyoss/symphony/messageml/elements/TextArea.java
src/main/java/org/symphonyoss/symphony/messageml/elements/TextField.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/TextAreaTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/TextFieldTest.java

See https://github.com/symphonyoss/messageml-utils/issues/177

MML-177 Elements Regex

---

src/main/java/org/symphonyoss/symphony/messageml/elements/Button.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/ButtonTest.java

MML-179 Fix error message related to allowed class attributes in a button

---

src/main/java/org/symphonyoss/symphony/messageml/elements/DatePicker.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/DatePickerTest.java

MML-218 Missing type=date

---

src/main/java/org/symphonyoss/symphony/messageml/elements/PersonSelector.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/PersonSelectorTest.java

Adding a new optional field in the PersonSelector Element. For more details: https://github.com/symphonyoss/messageml-utils/issues/236

MML-236 Add new attribute default value to PersonSelector

---

src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Element.java
src/main/java/org/symphonyoss/symphony/messageml/elements/TimePicker.java
src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/form/TimePickerNode.java
src/main/java/org/symphonyoss/symphony/messageml/util/pojo/TimeInterval.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/TimePickerTest.java

With this PR a new element called TimePicker is been implemented. More details on the new element can be found here: https://github.com/symphonyoss/messageml-utils/issues/238

MML-238 adding new element Time Picker

---

src/main/java/org/symphonyoss/symphony/messageml/elements/PersonSelector.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/PersonSelectorTest.java

Goal of this PR is to rename the "selected-user-ids" attribute into "value". This attribute should also be a valid array of Long type corresponding to a list of users ids

MML-236 renaming PersonSelector new attribute

---

src/main/java/org/symphonyoss/symphony/messageml/elements/Styles.java
src/test/java/org/symphonyoss/symphony/messageml/elements/StylesTest.java

MML-248 Unable to use base64 image in background-image style

---

src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Mention.java
src/main/java/org/symphonyoss/symphony/messageml/util/ShortID.java

Fix Sonar bugs (#250)

---

pom.xml

Closes https://github.com/symphonyoss/messageml-utils/issues/256

Release 0.9.68

---

src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
src/main/java/org/symphonyoss/symphony/messageml/bi/BiFields.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Dialog.java
src/main/java/org/symphonyoss/symphony/messageml/elements/DialogChild.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Element.java
src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/form/DialogNode.java
src/test/java/org/symphonyoss/symphony/messageml/elements/DialogTest.java

PLAT-10894: Dialog element

---

LICENSE
NOTICE
README.md
pom.xml
src/main/java/org/symphonyoss/symphony/messageml/MessageMLContext.java
src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Styles.java
src/main/java/org/symphonyoss/symphony/messageml/util/ShortID.java
src/main/java/org/symphonyoss/symphony/messageml/util/XmlPrintStream.java
src/test/java/org/symphonyoss/symphony/messageml/JmhBenchmarkRunner.java
src/test/java/org/symphonyoss/symphony/messageml/MessageMLContextBenchmark.java
src/test/java/org/symphonyoss/symphony/messageml/MessageMLContextTest.java

See https://perzoinc.atlassian.net/wiki/spaces/DevX/pages/2106428894/Agent+CPU+usage+investigations and individual commits for each change and the improvements.
Introduced JMH to micro benchmark the library (to be executed locally, making it part of CI would be a bit cosly IMHO).
https://perzoinc.atlassian.net/browse/PLAT-10987

PLAT-10987: Improve performances

---

src/main/java/org/symphonyoss/symphony/messageml/bi/BiFields.java
src/main/java/org/symphonyoss/symphony/messageml/elements/ExpandableCard.java
src/main/java/org/symphonyoss/symphony/messageml/elements/UIAction.java
src/test/java/org/symphonyoss/symphony/messageml/elements/ExpandableCardTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/UIActionTest.java

- Added the Dialog BI fields
- Removed **expandablecards** BI field
Closes #289

MML-289 Add uiactions_openim and uiactions_opendialog

---

pom.xml

(I squashed commits from 0.9.82 https://github.com/finos/messageml-utils/pull/316, an cannot create the release for this one)

Release 0.9.83

---

pom.xml

Bump versions 0.9.85

---

pom.xml
src/main/java/org/symphonyoss/symphony/messageml/elements/Code.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Element.java
src/test/java/org/symphonyoss/symphony/messageml/elements/CodeLanguageTest.java

Backport of #332 
Bumped version to 0.10.1

Pre tag backport

---

pom.xml
src/main/java/org/symphonyoss/symphony/messageml/elements/CashTag.java
src/main/java/org/symphonyoss/symphony/messageml/elements/HashTag.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Keyword.java
src/test/java/org/symphonyoss/symphony/messageml/elements/CashtagTest.java

Backport remove cashtag limitation + bump release version 

---

pom.xml

bump release version => 0.11.0

---

pom.xml

Update some dependencies

---

.github/workflows/build.yml
.github/workflows/release.yml

update github action version

---

pom.xml

set version 0.11.1

---

pom.xml
src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
src/test/java/org/symphonyoss/symphony/messageml/elements/LinkTest.java

[release] Prepare next release version

---

src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
src/main/java/org/symphonyoss/symphony/messageml/bi/BiFields.java
src/main/java/org/symphonyoss/symphony/messageml/elements/RoomSelector.java
src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/form/RoomSelectorNode.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/RoomSelectorTest.java

add room selector component (the same as person selector)

[AGNT-366][C2-20895] add room selector component

---

pom.xml
src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
src/main/java/org/symphonyoss/symphony/messageml/bi/BiFields.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Button.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Checkbox.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Code.java
src/main/java/org/symphonyoss/symphony/messageml/elements/DatePicker.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Element.java
src/main/java/org/symphonyoss/symphony/messageml/elements/GroupedElement.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Radio.java
src/main/java/org/symphonyoss/symphony/messageml/elements/RoomSelector.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Select.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Subscript.java
src/main/java/org/symphonyoss/symphony/messageml/elements/Superscript.java
src/main/java/org/symphonyoss/symphony/messageml/elements/TextArea.java
src/main/java/org/symphonyoss/symphony/messageml/elements/TextField.java
src/main/java/org/symphonyoss/symphony/messageml/elements/TimePicker.java
src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/form/RoomSelectorNode.java
src/test/java/org/symphonyoss/symphony/messageml/elements/CodeLanguageTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/SubscriptTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/SuperscriptTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/ButtonTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/CheckboxTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/DatePickerTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/RadioTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/RoomSelectorTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/SelectOptionTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/TextAreaTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/TextFieldTest.java
src/test/java/org/symphonyoss/symphony/messageml/elements/form/TimePickerTest.java

merge 0.12-rc into main branch
