finos/messageml-utils

- src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Button.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Element.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Form.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/FormElement.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Option.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Select.java
- src/main/java/org/symphonyoss/symphony/messageml/markdown/MarkdownRenderer.java
- src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/OptionNode.java
- src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/SelectNode.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/ButtonTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/SelectOptionTest.java
Problem: We need to support new Symphony Elements tag Select, that represents a dropdown menu.
Solution: Added the messageml validation and parsing into presentationml and markdown of the <select> and <option> tags. The validation assures the defined restrictions of the tag. Unit tests for the select tag were also added.
> MML-97 Add the Symphony Elements "option" and "select" tags

- src/main/java/org/symphonyoss/symphony/messageml/elements/Button.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Checkbox.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Form.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/PersonSelector.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Select.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/TextArea.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/TextField.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/ButtonTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/CheckboxTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/FormTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/PersonSelectorTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/RadioTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/SelectOptionTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/TextAreaTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/TextFieldTest.java
Fixes https://github.com/symphonyoss/messageml-utils/issues/142.
I also added unit tests for the elements (radio and action buttons) which are not currently failing.
> MML-142 - elements with required 'id' or 'name' attributes shouldn't allow blank values

- src/main/java/org/symphonyoss/symphony/messageml/elements/TextField.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/TextFieldTest.java
Adding validation to stop messages containing text-fields with an initial value bigger than the element's maxlength or smaller than its minlength
Fixes #145
> MML-145 - Validate maxlength and minlength on initial value for text-field attribute

- pom.xml
- src/main/java/org/symphonyoss/symphony/messageml/elements/Button.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/ButtonTest.java
If a user sends a Button with 'primary-destructive' or 'secondary-destructive' classes, we are converting it to 'primary' or 'secondary', respectively.
A info message will be shown in the Agent logs as
`2020-07-29 19:03:12,628 INFO  [org.symphonyoss.symphony.messageml.elements.Button] (https-jsse-nio-9443-exec-6) [Trace ID: OdZpMX] Button class cannot be a destructive one, replacing it accordingly.`
This is needed because the destructive values are deprecated and we don't accept them on the FE side anymore, so for now, we are just converting the values. In the future we will completely remove them and  prevent the user to send them.
> MML-203 - Changing Button class from 'primary-destructive' to 'primary' and 'secondary-destructive' to 'secondary'

- src/main/java/org/symphonyoss/symphony/messageml/elements/Mention.java
- src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/MentionNode.java
- src/main/java/org/symphonyoss/symphony/messageml/util/NoOpDataProvider.java
- src/main/java/org/symphonyoss/symphony/messageml/util/NullDataProvider.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/LinkTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/MentionTest.java
1. Adds a `NullDataProvider` which resolves all `<mention/>` inputs to empty strings and always validates URLs positively.
Usage:
```
String input = "<messageML>Hello <mention email=\"bot.user1@localhost.com\"/>!</messageML>";
IDataProvider nullProvider = new NullDataProvider();
MessageMLContext context = new MessageMLContext(nullProvider);
context.parseMessageML(input, null, MessageML.MESSAGEML_VERSION);
// context.getPresentationML();
String expectedPresentationML = "<div data-format=\"PresentationML\" data-version=\"2.0\">" +
"Hello <span class=\"entity\" data-entity-id=\"mention1\"></span>!" +
"</div>";
// context.getEntityJson();
String expectedJson = "{\"mention1\":{\"type\":\"com.symphony.user.mention\",\"version\":\"1.0\",\"id\":[{\"type\":\"com.symphony.user.userId\",\"value\":\"0 …
```
> MML-95 Add a No-Op Dataprovider

- src/main/java/org/symphonyoss/symphony/messageml/elements/DatePicker.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/DatePickerTest.java
Restrict possible date format placeholders to 'M', 'd', and 'y'. Right now it is possible to add seconds, minutes, etc, which can create issues and confusion.
> MML-227 Datepicker: Restrict format values

- src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
- src/test/java/org/symphonyoss/symphony/messageml/MessageMLContextTest.java
Currently in the MessageMLParser.java is not specifying the type of encoding that should be used while parsing a messageML, the goal of this issue is to change this behaviour to always use UTF-8 encoding.
Related issue: https://github.com/symphonyoss/messageml-utils/issues/229
> MML-229 using UTF-8 encoding while parsing MessageML

- .github/workflows/release.yml
- pom.xml
To preserve Git branch protection rules, the release workflow has been
changed to locally bump the versions, open a PR with the changes, get it
merged and from there create a GH release.
Then the workflow is triggered automatically and deploy the release on
Maven Central.
> PLAT-9093: PR based release workflow

- pom.xml
This PR is related to [PLAT-10552](https://perzoinc.atlassian.net/browse/PLAT-10552)
Snyk scan has reported a security issue with high severity in Freemarker module. Running the script test command locally, another issue related to Jackson-databind was found.
We fixed this by bumping dependency version from 2.3.28 to 2.3.30 and Jackson-databind from 2.10.1 to 2.10.5.1
> PLAT-10552 : bump Freemarker and Jackson-databind versions

- pom.xml
- src/main/java/org/symphonyoss/symphony/messageml/MessageMLContext.java
- src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
- src/main/java/org/symphonyoss/symphony/messageml/bi/BiContext.java
- src/main/java/org/symphonyoss/symphony/messageml/bi/BiItem.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Button.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Element.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Header.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Link.java
- src/test/java/org/symphonyoss/symphony/messageml/MessageMLContextTest.java
- src/test/java/org/symphonyoss/symphony/messageml/bi/BiContextTest.java
- src/test/java/org/symphonyoss/symphony/messageml/bi/BiItemTest.java
Goal of this PR is to set up a framework in order to be able collect BI events.
The BiContext is the main object which contains a list of BiItems (one per element found inside the messageML). While parsing the MessageML the BiContext will be initialised and automatically filled with all the information.
Each element will create a new BiItem which is composed by the element name and a map of all attributes found. To customise this item each element can override the updateBiContext() method of Element class and define the map as needed. 
For now the function is by default creating a simple item which counts the occurrences of the element inside the message. An example of custom biItem can be found in the Button class.
With the updateBiContext() inside element we will already get some …
> MML-258 Prepare messageml-utils to provide BiContext

- pom.xml
- src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Button.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/DatePicker.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/DateSelector.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Element.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Form.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/TimePicker.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/TimezonePicker.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/UIAction.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/UIActionTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/ButtonTest.java
Closes https://github.com/symphonyoss/messageml-utils/issues/261
Adding new messageML tag UIAction which is represented by the tag name "ui-action".
The messageML representation of this element can contain the following fields:
- trigger  -> default 'click', trigger of the action. For now only 'click' is supported
- action (required) -> action that can be executed on trigger. For now only 'open-im' is supported
- user-ids (exclusive with stream-id)-> list of the users we want the action to be applied on
- stream-id (exclusive with user-ids) -> stream we want the action to be applied on
- side-by-side -> default true, open the result chat in a new module and keeps the parent one open side by side. If false, the parent one will be replaced.
For now only Buttons and other UIActions will be …
> MML-261 Adding new UIAction tag in MessageML

- src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
Freemarker now logs a warning when Configuration.getVersion() is used, a
specific version should be used instead.
See https://freemarker.apache.org/docs/pgui_config_incompatible_improvements.html
Use the current version that we get as a dependency (that what is
returned by getVersion() now).
> Avoid Freemarker warning in logs

- src/main/java/org/symphonyoss/symphony/messageml/elements/Dialog.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/DialogTest.java
`<dialog open>` is valid HTML whereas it is invalid XML, hence the confusion. Replaced that with `<dialog open="">`
> PLAT-10894: Added empty string as attribute of open in dialog

- src/main/java/org/symphonyoss/symphony/messageml/elements/Button.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/DialogTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/ButtonTest.java
This PR is related to #285 
In order to support new dialog element, button should support 'cancel' type. A new type was added to the supported ones. Button's name is set to required for it.
> Update Button Element to support 'cancel' type

- src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Dialog.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/DialogChild.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Element.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Form.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/DialogTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/UIActionTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/FormTest.java
The ticket name is "Update Form Element" but most of the changes were done in the dialog element.
From the [spec documentation](https://perzoinc.atlassian.net/wiki/spaces/DevX/pages/1986267475/Element+Dialog+-+MessageML+PresentationML+Form+Reply+Content+Export#Form-Element):
-  No Element can be inserted inside a dialog without being wrapped by the <form> tag (starting and finishing in the dialog)
- Only <title>, <body>, and <footer> tags are accepted at the root level in a form tag that is wrapped by a dialog.
- A dialog can only accept 1 form
- A form can contain multiple dialog tags
- A dialog in a form can’t contain a form (already implemented in the Form validation.)
> PLAT-11049 Update Form Element

- src/main/java/org/symphonyoss/symphony/messageml/bi/BiFields.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Form.java
- src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/EmojiNode.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/FormTest.java
Goal of this PR is to add a new attribute to the form element called "multi-submit". This attribute accepts only two values depending if the user wants to reset or not the previous submit input. More info on this are available here: https://github.com/symphonyoss/messageml-utils/issues/291.
Also a new BI item hs been introduce to track usage of multi-submit forms.
Closes #291
> MML-291 Add multi-submit attribute to form element

- src/main/java/org/symphonyoss/symphony/messageml/elements/Dialog.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Element.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Form.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/MessageML.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/UIAction.java
- src/test/java/org/symphonyoss/symphony/messageml/MessageMLContextBenchmark.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/DialogTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/UIActionTest.java
Goal of this PR is to fix some minor issues found during validation.
- Allowing the presence of whitespaces inside the Dialog element
- If a UIAction with a target-id referring to a Dialog comes in the messageML before the Dialog itself, the message should be allowed and parsed correctly.
- No more that one form is allowed inside a Dialog element
- We should be able to match Dialog-UIAction target id even if they are nested inside another element.
- Matching Dialog-UiAction should be in the same scope (at the same level of the messageML tree) to be valid.
Closes #295
> MML-294 Fixing some issued with the UIAction and Dialog elements

- src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
- src/test/java/org/symphonyoss/symphony/messageml/MessageMLContextTest.java
If a string (i.e valid JSON) is provided as data (invalid EntityJSON)
a ClassCastException was raised. This is now handled as an
InvalidInputException with a better error message.
> Error handling for EntityJson parsing

- pom.xml
```
✗ XML External Entity (XXE) Injection [High Severity][https://snyk.io/vuln/SNYK-JAVA-ORGMOZILLA-1314295] in org.mozilla:rhino@1.7.7.1
introduced by org.symphonyoss.symphony:messageml@0.9.70 > com.github.java-json-tools:json-schema-validator@2.2.10 > com.github.java-json-tools:json-schema-core@1.2.10 > org.mozilla:rhino@1.7.7.1
This issue was fixed in versions: 1.7.12
```
Latest available `json-schema-validator` (2.2.14, released May 2020) ships with an unsafe Rhino version. Need to add an exclusion and pull in a safe Rhino version explicitly.
> MML-298 Fix XXE in json-schema-validator

- pom.xml
Default value was 5 minutes, [sonatype](https://status.maven.org) seems to be overloaded (#log4shell), hopefully increasing it to 10 minutes will allow us to release the library.
> Increased nexus stagingProgressTimeoutMinutes to 10 minutes

- src/main/java/org/symphonyoss/symphony/messageml/elements/MessageML.java
- src/test/java/org/symphonyoss/symphony/messageml/MessageMLContextTest.java
As a future potential improvement, we'd introduce a XML Schema for MessageML format. We would then need to accept messages like: 
```xml
<messageML xmlns="https://finos.org/messageml">
<h1>Hello, World!</h1>
</messageML>
```
Here we make sure that we at least support the `xmlns` attribute as earlier as possible, waiting for all Agents to be updated until we really release MessageML XML Schema.
> MessageML tag accepts xmlns attribute

- pom.xml
- src/main/java/org/symphonyoss/symphony/messageml/elements/Element.java
- src/test/java/org/symphonyoss/symphony/messageml/markdown/MarkdownParserTest.java
PR related to [PLAT-11690](https://perzoinc.atlassian.net/browse/PLAT-11690)
Some developers recently noticed that [Agent API Bridge](https://docs.developers.symphony.com/admin-guide/agent-guide) was returning error: 
```
Unable to process message with ID xxx in stream xxx due to: Failed to build Markdown: Parent of block must also be block (can not be inline)
```
The issue is happening when Agent receives replied or forwarded messages since those ones are sent in Markdown format from the Symphony Clients (Mana or 1.5). 
This PR contains an example used to reproduce the issue. More examples and more testing will need to be done regarding the Markdown parsing capability of the library.
> Fixed a bug occurring while parsing Markdown generated by Symphony Client

- src/main/java/org/symphonyoss/symphony/messageml/elements/Code.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Element.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/CodeLanguageTest.java
Client was generating following PresentationML that was not considered valid by messageml-utils:
```xml
<div data-format="PresentationML" data-version="2.0">
<code data-language="plaintext"><pre>Hello</pre></code>
</div>
```
> Allowed <pre> tag in a <code> one

- src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
- src/test/java/org/symphonyoss/symphony/messageml/MessageMLContextTest.java
Goal of this implementation is to add BiItems in the BiContext for custom entities as well.
For each custom entity found in the entityJson payload we
- create a BiItem containing the type of entity found
- increase the total count of entities found in the message
> Adding Bi Items for Custom entities

- pom.xml
- src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
- src/test/java/org/symphonyoss/symphony/messageml/MessageMLContextTest.java
Cherry-pick of https://github.com/finos/messageml-utils/pull/334
Goal of this implementation is to add BiItems in the BiContext for custom entities as well.
For each custom entity found in the entityJson payload we
- create a BiItem containing the type of entity found
- increase the total count of entities found in the message
> Backport Adding Bi Items for Custom entities (#334) and release

- src/main/java/org/symphonyoss/symphony/messageml/bi/BiFields.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Option.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Select.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/SelectOptionTest.java
Option counts inside a dropdown menu should not generate a bi metric by its own. Goal of this PR is to include the options_count + the defauld field as part of the same Bi Item containing the dropdown menu.
> Removing Option Bi Item and include fields in Dropdown

- pom.xml
- src/main/java/org/symphonyoss/symphony/messageml/bi/BiFields.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Option.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Select.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/SelectOptionTest.java
> Backport removing option Bi Item + bump release version

- src/main/java/org/symphonyoss/symphony/messageml/elements/CashTag.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/HashTag.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Keyword.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/CashtagTest.java
Removing the regex limitation we currently enforce on cashtags format, starting from now we'll start accepting cashtags containing whitespaces and numeric-only tags.
> Removing cashtag regex limitation

- allow-list.xml
As suggested by Finos organisation, removed unused allow-list entries
The only remaining one is CVE-2021-29425 which only fix is not to use the method createTempDir(). We do not use this method in our project this is a false positive.
> Removed most allowed cves from allow list

- pom.xml
- src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
- src/main/java/org/symphonyoss/symphony/messageml/markdown/MarkdownRenderer.java
- src/test/resources/payloads/expanded_single_jira_ticket.entities
fix link entity index end
ignore semgrep rule : owasp.java.xxe.javax.xml.parsers.DocumentBuilderFactory   
> [AGNT-264] fix link entity indexEnd

- src/main/java/org/symphonyoss/symphony/messageml/MessageMLParser.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Element.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Subscript.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Superscript.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/SubscriptTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/SuperscriptTest.java
> [AGNT-319] support <sup> and <sub> tags

- src/main/java/org/symphonyoss/symphony/messageml/elements/Code.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/CodeLanguageTest.java
> [AGNT-333] add extra supported language to <code> tag

- src/main/java/org/symphonyoss/symphony/messageml/elements/Select.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/TextField.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/SelectOptionTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/TextFieldTest.java
[AGNT-366][C2-20892] add auto-submit attribute to select and text-field component
> [AGNT-366][C2-20892] support auto-submit attribute

- src/main/java/org/symphonyoss/symphony/messageml/elements/TextArea.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/TextAreaTest.java
> [AGNT-366][C2-20894] support rows and cols atributes  for textarea

- src/main/java/org/symphonyoss/symphony/messageml/elements/Button.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/ButtonTest.java
Add support to icon attribute 
add two more supported classes : `primary-link` - `destructive-link`
> [AGNT-366][C2-20898] add icon attribute and support more classes

- src/main/java/org/symphonyoss/symphony/messageml/elements/Checkbox.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/DatePicker.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/GroupedElement.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Radio.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/Select.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/TextArea.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/TextField.java
- src/main/java/org/symphonyoss/symphony/messageml/elements/TimePicker.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/CheckboxTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/DatePickerTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/RadioTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/SelectOptionTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/TextAreaTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/TextFieldTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/TimePickerTest.java
add support to disabled and readonly attributes for the following components:
checkbox radio date-picker select textarea text-field  time-picker
> [AGNT-366][C2-20897] support disabled or readonly attributes

- src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/TableCellNode.java
- src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/TableNode.java
- src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/form/CheckboxNode.java
- src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/form/FormNode.java
- src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/form/RadioNode.java
- src/main/java/org/symphonyoss/symphony/messageml/markdown/nodes/form/SelectNode.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/TableTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/ButtonTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/CheckboxTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/DatePickerTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/DateSelectorTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/PersonSelectorTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/RadioTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/RoomSelectorTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/SelectOptionTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/TextAreaTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/TextFieldTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/TimePickerTest.java
- src/test/java/org/symphonyoss/symphony/messageml/elements/form/TimezonePickerTest.java
- src/test/resources/payloads/expanded_single_jira_ticket.entities
- src/test/resources/payloads/expanded_single_jira_ticket.markdown
> AGNT-397 edit table  and elements markdown representation
